#!/usr/bin/env bash
# Build ~/.config/quickshell/caelestia as an overlay of the packaged Caelestia shell.
#
# Everything is a symlink into /etc/xdg/quickshell/caelestia except:
#   - the two patched files (modules/bar/Bar.qml, modules/bar/popouts/Content.qml)
#   - aiusage/ -> this project's QML
# Quickshell prefers the user config dir, so `qs -c caelestia` picks this up.
# Re-run after every caelestia-shell upgrade so the patched copies track upstream.
#
# Usage: ./install.sh [--uninstall] [--restart]
#   --restart  restart the shell afterwards. `caelestia shell -k` alone can't do
#              this across the switch: qs finds instances by config path, and the
#              path changes between /etc/xdg and ~/.config.
set -euo pipefail
shopt -s dotglob nullglob

UNINSTALL=0 RESTART=0
for arg in "$@"; do
    case $arg in
    --uninstall) UNINSTALL=1 ;;
    --restart) RESTART=1 ;;
    *) echo "usage: $0 [--uninstall] [--restart]" >&2 && exit 2 ;;
    esac
done

SRC=${CAELESTIA_SRC:-/etc/xdg/quickshell/caelestia}
DST=${XDG_CONFIG_HOME:-$HOME/.config}/quickshell/caelestia
BIN=$HOME/.local/bin/ai-usage
HERE=$(cd "$(dirname "$(readlink -f "$0")")" && pwd)
MARKER=.ai-usage-overlay
PATCHED=(modules/bar/Bar.qml modules/bar/popouts/Content.qml)

die() {
    echo "error: $*" >&2
    exit 1
}

# Refuse to touch a user config we didn't create.
if [[ -e $DST && ! -e $DST/$MARKER ]]; then
    die "$DST exists and is not an ai-usage overlay; not touching it"
fi

stop_shell() {
    ((RESTART)) || return 0
    qs kill -p "$SRC" >/dev/null 2>&1 || true
    if [[ -e $DST ]]; then
        qs kill -p "$DST" >/dev/null 2>&1 || true
    fi
    # qs kill returns before the process is gone, and `caelestia shell -d` uses
    # --no-duplicate, so starting too early silently does nothing.
    local _
    for _ in {1..50}; do
        qs list --all 2>/dev/null | grep -qE "Config path: ($SRC|$DST)/shell.qml" || return 0
        sleep 0.1
    done
    echo "warning: old shell instance still running" >&2
}

start_shell() {
    if ((RESTART)); then
        caelestia shell -d >/dev/null 2>&1
        echo "Shell restarted."
    else
        echo "Restart the shell to apply (or re-run with --restart)."
    fi
}

if ((UNINSTALL)); then
    stop_shell
    rm -rf "$DST"
    if [[ -L $BIN ]]; then rm "$BIN"; fi
    echo "Removed overlay; the packaged Caelestia config is used again."
    start_shell
    exit 0
fi

[[ -f $SRC/shell.qml ]] || die "Caelestia shell not found at $SRC"

mkdir -p "$(dirname "$DST")"
TMP=$(mktemp -d "${DST}.new.XXXXXX")
trap 'rm -rf "$TMP"' EXIT

is_patched() {
    local p
    for p in "${PATCHED[@]}"; do [[ $p == "$1" ]] && return 0; done
    return 1
}

contains_patched() {
    local p
    for p in "${PATCHED[@]}"; do [[ $p == "$1"/* ]] && return 0; done
    return 1
}

# mirror <relative dir>: symlink everything, descending only into dirs that hold a patched file.
mirror() {
    local rel=$1 src name path
    mkdir -p "$TMP/$rel"
    for src in "$SRC/$rel"*; do
        name=${src##*/}
        path=$rel$name
        if is_patched "$path"; then
            install -m 644 "$src" "$TMP/$path"
            patch --silent --no-backup-if-mismatch "$TMP/$path" "$HERE/shell/patches/$name.patch" ||
                die "patch for $path no longer applies (Caelestia changed it); update shell/patches/$name.patch"
        elif [[ -d $src ]] && contains_patched "$path"; then
            mirror "$path/"
        else
            ln -s "$src" "$TMP/$path"
        fi
    done
}

mirror ""
ln -s "$HERE/shell/aiusage" "$TMP/aiusage"
echo "Overlay of $SRC generated by $HERE/install.sh" >"$TMP/$MARKER"

stop_shell
rm -rf "$DST"
mv "$TMP" "$DST"
trap - EXIT

mkdir -p "$(dirname "$BIN")"
ln -sfn "$HERE/bin/ai-usage" "$BIN"

echo "Installed overlay at $DST"
start_shell
